# Generated by Django 4.2.16 on 2026-06-25 13:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(db_index=True, decimal_places=2, help_text='Price in Indian Rupees (₹)', max_digits=10)),
                ('negotiable', models.BooleanField(default=True)),
                ('condition', models.CharField(choices=[('new', 'Brand New'), ('like_new', 'Like New'), ('good', 'Good'), ('fair', 'Fair'), ('defective', 'Defective')], default='good', max_length=20)),
                ('location_name', models.CharField(help_text='Human-readable address or area', max_length=255)),
                ('district', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(db_index=True, max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('available', 'Available'), ('pending', 'Pending'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('expired', 'Expired'), ('unlisted', 'Unlisted (24h Missed)'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='available', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('views_count', models.IntegerField(default=0)),
                ('buy_request_count', models.IntegerField(default=0)),
                ('listed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_buy_request_at', models.DateTimeField(blank=True, null=True)),
                ('seller_action_deadline', models.DateTimeField(blank=True, help_text='24h deadline after a buy request', null=True)),
                ('unlisted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When listing expires (configurable)', null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='categories.category')),
            ],
            options={
                'ordering': ['-listed_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='products/')),
                ('public_id', models.CharField(blank=True, help_text='Cloudinary public_id for deletion', max_length=255)),
                ('display_order', models.IntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'ordering': ['display_order', 'uploaded_at'],
            },
        ),
    ]
