# Generated by Django 4.2.16 on 2026-06-25 13:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('fraud', 'Fraud / Scam'), ('fake_product', 'Fake Product'), ('abuse', 'Abusive Behaviour'), ('spam', 'Spam Listing'), ('prohibited', 'Prohibited Item'), ('other', 'Other')], db_index=True, max_length=30)),
                ('description', models.TextField()),
                ('evidence_image', models.ImageField(blank=True, null=True, upload_to='complaints/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('warned', 'User Warned'), ('suspended', 'User Suspended'), ('banned', 'User Banned'), ('dismissed', 'Dismissed'), ('resolved', 'Resolved')], db_index=True, default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('resolution', models.TextField(blank=True)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
