# Generated by Django 4.2.16 on 2026-06-25 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_type', models.CharField(choices=[('aadhaar', 'Aadhaar'), ('pan', 'PAN Card'), ('driving_license', 'Driving License'), ('voter_id', 'Voter ID'), ('passport', 'Passport')], max_length=30)),
                ('id_number', models.CharField(blank=True, max_length=100)),
                ('id_front_image', models.ImageField(upload_to='verification/')),
                ('id_back_image', models.ImageField(blank=True, null=True, upload_to='verification/')),
                ('selfie_image', models.ImageField(blank=True, null=True, upload_to='verification/')),
                ('whatsapp_number', models.CharField(max_length=15)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('country', models.CharField(default='India', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resubmitted', 'Resubmitted')], db_index=True, default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['status'], name='verificatio_status_3cdd63_idx'), models.Index(fields=['user', 'status'], name='verificatio_user_id_63a96e_idx')],
            },
        ),
    ]
