# Generated by Django 4.2.16 on 2026-06-25 13:29

import apps.users.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email address')),
                ('full_name', models.CharField(max_length=255, verbose_name='full name')),
                ('mobile_number', models.CharField(db_index=True, max_length=15, unique=True, verbose_name='mobile number')),
                ('whatsapp_number', models.CharField(blank=True, max_length=15, verbose_name='WhatsApp number')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='bio')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('district', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='district')),
                ('state', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='state')),
                ('country', models.CharField(default='India', max_length=100, verbose_name='country')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('email_verified', models.BooleanField(default=False, verbose_name='email verified')),
                ('mobile_verified', models.BooleanField(default=False, verbose_name='mobile verified')),
                ('verified_seller', models.BooleanField(default=False, verbose_name='verified seller')),
                ('verified_seller_badge_date', models.DateTimeField(blank=True, null=True)),
                ('is_suspended', models.BooleanField(default=False, verbose_name='suspended')),
                ('is_banned', models.BooleanField(default=False, verbose_name='banned')),
                ('suspended_until', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('moderator', 'Moderator'), ('admin', 'Admin')], db_index=True, default='user', max_length=20, verbose_name='role')),
                ('last_active', models.DateTimeField(blank=True, null=True, verbose_name='last active')),
                ('joined_date', models.DateTimeField(auto_now_add=True, verbose_name='joined date')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', apps.users.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login Failed'), ('register', 'Register'), ('password_change', 'Password Change'), ('password_reset', 'Password Reset'), ('otp_request', 'OTP Request'), ('otp_verify', 'OTP Verify'), ('profile_update', 'Profile Update'), ('suspend', 'Suspend'), ('ban', 'Ban')], max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'action'], name='users_usera_user_id_6525b9_idx')],
            },
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('code', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('email_register', 'Email Registration'), ('email_login', 'Email Login'), ('mobile_verify', 'Mobile Verification'), ('password_reset', 'Password Reset')], default='email_register', max_length=30)),
                ('is_used', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code', 'purpose'], name='users_otpve_code_909ed5_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['district', 'state'], name='users_user_distric_41f90f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['verified_seller'], name='users_user_verifie_c88f41_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_suspended'], name='users_user_is_susp_7493fe_idx'),
        ),
    ]
