# Generated by Django 4.2.16 on 2026-06-25 13:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('buyer_name', models.CharField(max_length=200)),
                ('buyer_phone', models.CharField(max_length=15)),
                ('buyer_whatsapp', models.CharField(blank=True, max_length=15)),
                ('buyer_location', models.CharField(blank=True, max_length=255)),
                ('buyer_message', models.TextField(blank=True)),
                ('offered_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20)),
                ('seller_response', models.TextField(blank=True)),
                ('seller_responded_at', models.DateTimeField(blank=True, null=True)),
                ('deadline_at', models.DateTimeField(help_text='24h deadline for seller response')),
                ('expired_notification_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
