# Generated by Django 4.2.16 on 2026-06-25 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buy_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyrequest',
            name='buyer',
            field=models.ForeignKey(blank=True, help_text='Null if buyer is not a registered user (guest).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buy_requests_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buyrequest',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_requests', to='products.product'),
        ),
        migrations.AddIndex(
            model_name='buyrequest',
            index=models.Index(fields=['product', 'status'], name='buy_request_product_44ba69_idx'),
        ),
        migrations.AddIndex(
            model_name='buyrequest',
            index=models.Index(fields=['buyer', '-created_at'], name='buy_request_buyer_i_a0affc_idx'),
        ),
        migrations.AddIndex(
            model_name='buyrequest',
            index=models.Index(fields=['status', 'deadline_at'], name='buy_request_status_722e8b_idx'),
        ),
    ]
