# Generated by Django 4.2.16 on 2026-06-27 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buy_requests', '0003_buyrequest_product_created_index'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='buyrequest',
            new_name='buy_request_product_dfbc6e_idx',
            old_name='buy_request_product_created_idx',
        ),
    ]
