# Generated by Django 4.2.16 on 2026-06-25 13:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBanner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.URLField(blank=True)),
                ('link_text', models.CharField(default='Learn More', max_length=100)),
                ('background_color', models.CharField(default='#0EA5E9', max_length=20)),
                ('text_color', models.CharField(default='#FFFFFF', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_dismissible', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('value', models.TextField()),
                ('value_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('boolean', 'Boolean'), ('json', 'JSON')], default='string', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(db_index=True, default='general', max_length=50)),
                ('is_editable', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'key'],
            },
        ),
        migrations.CreateModel(
            name='ThemeConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#0EA5E9', max_length=20)),
                ('secondary_color', models.CharField(default='#6366F1', max_length=20)),
                ('accent_color', models.CharField(default='#F59E0B', max_length=20)),
                ('success_color', models.CharField(default='#10B981', max_length=20)),
                ('danger_color', models.CharField(default='#EF4444', max_length=20)),
                ('background_color', models.CharField(default='#F8FAFC', max_length=20)),
                ('surface_color', models.CharField(default='#FFFFFF', max_length=20)),
                ('text_primary_color', models.CharField(default='#0F172A', max_length=20)),
                ('text_secondary_color', models.CharField(default='#64748B', max_length=20)),
                ('dark_mode_background', models.CharField(default='#0F172A', max_length=20)),
                ('dark_mode_surface', models.CharField(default='#1E293B', max_length=20)),
                ('dark_mode_text_primary', models.CharField(default='#F8FAFC', max_length=20)),
                ('dark_mode_text_secondary', models.CharField(default='#94A3B8', max_length=20)),
                ('homepage_layout', models.CharField(default='default', help_text='default | compact | grid', max_length=50)),
                ('show_featured_section', models.BooleanField(default=True)),
                ('show_recent_section', models.BooleanField(default=True)),
                ('show_categories_section', models.BooleanField(default=True)),
                ('show_banner', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Theme Configuration',
                'verbose_name_plural': 'Theme Configuration',
            },
        ),
    ]
